#!/bin/bash

PROGNAME=$(basename $0)
VERSION="0.1.0"
Errmsg="[1;31m[error][0m"
Sccmsg="[1;32m[success][0m"
Modidate="2020-05-11"
incmd="$0 $*"


# {{{ usage
read -r -d '' usage <<EOF
[1;35m### $PROGNAME ver $VERSION ($Modidate) ###[0m

[1;32m[description][0m
$PROGNAME - Pipeline for phylogenetic placement.
$PROGNAME is developed as a tool for phylogenetic placement onto a clade or taxonomy defined phylogenetic tree through procedures below. Very large queries are acceptable.

1. prefilter query sequences by similarity detection (hmmsearch). Queries and references should be protein sequences at this moment.
2. align query sequences to a given reference alignment ('mafft --add' [or 'hmmalign': not implemented yet])
3. perform phylogenetic placement ('pplacer' [or 'epa-ng': not implemented yet]) with efficient parallelization ('gappa prepare chunkify' and 'gappa prepare unchunkify')
4. analysis of placed sequences 
  a. assign clade/taxonomy and generate statistics ('gappa examine assign')
  b. extract placed sequences and placement file for each  clade/taxonomy ('gappa prepare extract')
  c. extract placed sequences and placement file for each  clade/taxonomy ('gappa prepare extract')

[1;32m[usage][0m
$ $PROGNAME [options] -q <query fasta(s)> -r <refpkg dir(s)> -o <output dir>

[1;32m[dependencies][0m
- hmmer (ver >= 3.0)
- mafft (tested by 7.453)
- gappa (tested by 0.6.0)
- pplacer (tested by 1.1.alpha19)
- ruby (ver >= 2.0) 

[1;32m[options][0m
  (general)
    -h, --help
    -v, --version

  (file/directory)
    -q, --query      [file(s)] (required)  -- query sequence file(s) (currently protein only)
                                              Multiple query file can be specfied with wildcard (e.g., 'dir/*.fa', quote required) or comma separated values (e.g., A.fa,B.fa).
                                              File names should be unique (used as output labels).
    -r, --refpkg     [dir(s)] (required)   -- reference package(s) made by taxtastic as 'taxit create -P <name> --tree-file <newick file> --tree-stats <file>', for example.
                                              The directory must contain additional 2 files:
                                              - aligned sequence (.fa, .mfa, or .fasta),
                                              - its hmm model (.hmm, made by 'hmmbuild')
                                              For full functionality, it is recommended that the directory contains additional 2 files:
                                              - taxon file ('taxon.tsv' -- 1. sequence_id, 2. clade or taxonomy) used by '--taxon-file <tsv>' of 'gappa examine assign'
                                              - alignment check file ('position.tsv' -- 1. label, 2. position(s) in alignment, which can be multiple per a label by using ',' as a separator)
                                                to check important positions in sequence alignment

                                              Multiple Reference packages can be specfied with wildcard (e.g., 'dir/*', quate required) or comma separated values (e.g., A,B).
                                              Directory names should be unique (used as output labels).
                                              Note that each query is placed onto at most one tree that is most significantly related among refpkgs (in terms of hmmsearch evalue).

                                              Further information
                                              - taxtastic: https://github.com/fhcrc/taxtastic
                                              - gappa examine assign: https://github.com/fhcrc/taxtasti://github.com/lczech/gappa/wiki/Subcommand:-assign 
    -o, --outdir     [path] (required)     -- output directory (should not exist unless '--overwrite' is specified)
    --overwrite      [bool]                -- overwrite output directory

  (mode)
    --only-detect    [bool]                -- only detect target sequence and extract hit region

  (prefilter)
    -e, --evalue     [num] (default: 1e-5) -- evalue threshold of hmmsearch
    --minseqlen      [int] (default: 0)    -- minimum query aa length
    --minhmmlen      [int] (default: 0)    -- minimum hmm length in alignment of hmmsearch
    --trim-option    [merge or largest] (default: merge) -- take merged regions of hmmsearch hits (if multiple) or take largest hit

  (align)
    --mafft-method   [FFT-NS-2 or E-INS-i] (default: FFT-NS-2) -- mafft method used with '--add' and '--keeplength'.
                                                                  It can be either '--retree 2' (FFT-NS-2, faster) or '--genafpair' (E-INS-i, more accurate).
                                                                  For more details, see https://mafft.cbrc.jp/alignment/software/algorithms/algorithms.html.

  (extract)
    --extract-levels [int(s)] (default: 0) -- specify level of clade/taxonomy (written in the second column of TSV file in refpkg) to extract each clade/taxonomy placement.
                                              (e.g., 'Eukaryota; Amoebozoa; Myxogastria' has three levels. '--extract-levels 3' means 'Myxogastria' will be extracted.)
                                              Multiple levels can be specified with comma separeted values (e.g., '--extract-levels 2,3').
                                               '0' means all levels in the TSV file. '-1' means extraction is not performed.

  (computation)
    -c, --chunk-size [int] (default: 3000) -- chunk size of 'gappa prepare chunkify'. If the value is lower, smaller batch jobs (that can be parallelized) will be generated.
                                              Note that it is not efective to have very low value (e.g., less than 1,000)
    -n, --ncpus      [int] (default: 1)    -- num CPUs to use (for multicore computation, 'parallel' (GNU parallel) need to be available.)

[1;32m[output files][0m
  result/<refpkg name>/{all,each}/{query,alignment,placement,assign,extract,...} -- result of placement and further analysis
EOF
# }}} usage


# {{{ parse command line
for OPT in "$@"
do
	case "$OPT" in
		'-h'|'--help' )
			echo "$usage"
			exit 1
			;;
		'-v'|'--version' )
			echo $VERSION
			exit 1
			;;
		'-q'|'--query' )
			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]] ; then
				echo "$Errmsg option requires an argument -- $1" 1>&2; exit 1
			fi
			query="$2"
			shift 2
			;;
		'-r'|'--refpkg' )
			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]] ; then
				echo "$Errmsg option requires an argument -- $1" 1>&2; exit 1
			fi
			refpkg="$2"
			shift 2
			;;
		'-o'|'--outdir' )
			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]] ; then
				echo "$Errmsg option requires an argument -- $1" 1>&2; exit 1
			fi
			outdir="$2"
			shift 2
			;;
		'--overwrite' )
			overwrite=true
			shift 1
			;;
		'--only-detect' )
			only_detect=true
			shift 1
			;;
		'-e'|'--evalue' )
			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]] ; then
				echo "$Errmsg option requires an argument -- $1" 1>&2; exit 1
			fi
			evalue="$2"
			shift 2
			;;
		'--minseqlen' )
			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]] ; then
				echo "$Errmsg option requires an argument -- $1" 1>&2; exit 1
			fi
			minseqlen="$2"
			shift 2
			;;
		'--minhmmlen' )
			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]] ; then
				echo "$Errmsg option requires an argument -- $1" 1>&2; exit 1
			fi
			minhmmlen="$2"
			shift 2
			;;
		'--trim-option' )
			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]] ; then
				echo "$Errmsg option requires an argument -- $1" 1>&2; exit 1
			fi
			trim_option="$2"
			shift 2
			;;
		'--mafft-method' )
			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]] ; then
				echo "$Errmsg option requires an argument -- $1" 1>&2; exit 1
			fi
			mafft_method="$2"
			shift 2
			;;
		'--extract-levels' )
			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]] ; then
				echo "$Errmsg option requires an argument -- $1" 1>&2; exit 1
			fi
			extract_levels="$2"
			shift 2
			;;
		'-c'|'--chunk-size' )
			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]] ; then
				echo "$Errmsg option requires an argument -- $1" 1>&2; exit 1
			fi
			chunk_size="$2"
			shift 2
			;;
		'-n'|'--ncpus' )
			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]] ; then
				echo "$Errmsg option requires an argument -- $1" 1>&2; exit 1
			fi
			ncpus="$2"
			shift 2
			;;
		'--'|'-' )
			shift 1
			params+=( "$@" )
			break
			;;
		-*)
			echo "$Errmsg illegal option -- '$(echo $1 | sed 's/^-*//')'" 1>&2; exit 1
			;;
		*)
			if [[ ! -z "$1" ]] && [[ ! "$1" =~ ^-+ ]] ; then
				echo "$Errmsg unparsable argument ($1)." 1>&2; echo "        Note: do not forget quotation marks to use wildcards" 1>&2; exit 1
			fi
			;;
	esac
done

## default
evalue="${evalue:-1e-5}"
ncpus="${ncpus:-1}"
chunk_size="${chunk_size:-3000}"
minseqlen="${minseqlen:-0}"
minhmmlen="${minhmmlen:-0}"
trim_option="${trim_option:-merge}"
mafft_method="${mafft_method:-FFT-NS-2}"
extract_levels="${extract_levels:-0}"

re='^[0-9]+$'
if   [[ ! -n "$query" ]] ; then
	echo "$Errmsg  -q, --query <fasta file(s)> should be given." 1>&2; echo "         execute '$PROGNAME -h' for usage" 1>&2; exit 1
elif [[ ! -n "$refpkg" ]] ; then
	echo "$Errmsg  -r, --refpkg <refpkg dir(s)> should be given." 1>&2; echo "         execute '$PROGNAME -h' for usage" 1>&2; exit 1
elif [[ ! -n "$outdir" ]] ; then
	echo "$Errmsg  -o, --outdir should be given." 1>&2; echo "         execute '$PROGNAME -h' for usage" 1>&2; exit 1
elif [[   -d "$outdir" && -z "$overwrite" ]] ; then
	echo "$Errmsg  -o, --outdir $outdir already exists. Use --overwrite to overwrite it. " 1>&2; echo "         execute '$PROGNAME -h' for usage" 1>&2; exit 1
elif [[ ! -d "$outdir" &&  -e "$outdir" ]] ; then
	echo "$Errmsg  -o, --outdir $outdir already exists and not directory (is it a file?). " 1>&2; echo "         execute '$PROGNAME -h' for usage" 1>&2; exit 1
elif [[ ! $chunk_size =~ $re ]] ; then
	echo "$Errmsg  -c, --chunk-size '$chunk_size' is not an integer" 1>&2; echo "         execute '$PROGNAME -h' for usage" 1>&2; exit 1
elif [[   "$mafft_method" != "FFT-NS-2" ]] && [[ "$mafft_method" != "E-INS-i" ]] ; then
	echo "$Errmsg  --mafft-method should be either FFT-NS-2 or E-INS-i ('$mafft_method' is given)." 1>&2; echo "         execute '$PROGNAME -h' for usage" 1>&2; exit 1
elif [[ ! $ncpus =~ $re ]] ; then
	echo "$Errmsg  --ncpus '$ncpus' is not an integer" 1>&2; echo "         execute '$PROGNAME -h' for usage" 1>&2; exit 1
elif [[ ! $minseqlen =~ $re ]] ; then
	echo "$Errmsg  --minseqlen '$minseqlen' is not an integer" 1>&2; echo "         execute '$PROGNAME -h' for usage" 1>&2; exit 1
elif [[ ! $minhmmlen =~ $re ]] ; then
	echo "$Errmsg  --minhmmlen '$minhmmlen' is not an integer" 1>&2; echo "         execute '$PROGNAME -h' for usage" 1>&2; exit 1
fi

if [[ -d "$outdir" && "$overwrite" = "true" ]] ; then
	outdir_exist=true
fi

### rakefile/logdir
pushd `dirname $0` > /dev/null
scrdir=`pwd -P`
popd > /dev/null
jobname=`basename $0`
rakefile=$scrdir/$jobname.rake

logdir=$outdir/log
mkdir -p $logdir
startTime=$(LC_ALL=C date +"%Y-%m-%d_%H:%M:%S")
flog=$logdir/$startTime.$jobname.log
# }}} parse command line


# {{{ check dependencies
command -v hmmsearch >/dev/null 2>&1 || { echo >&2 "$Errmsg hmmsearch (hmmer) is not available.  Aborting."; exit 1; }
command -v mafft >/dev/null 2>&1 || { echo >&2 "$Errmsg mafft is not available.  Aborting."; exit 1; }
command -v gappa >/dev/null 2>&1 || { echo >&2 "$Errmsg gappa is not available.  Aborting."; exit 1; }
# command -v pplacer >/dev/null 2>&1 || { echo >&2 "$Errmsg pplacer is not available.  Aborting."; exit 1; }
command -v ruby >/dev/null 2>&1 || { echo >&2 "$Errmsg ruby is not available.  Aborting."; exit 1; }

### check ruby version
ST=`ruby -e 'print RUBY_VERSION.to_f >= 2.0 ? 0 : 1'`
if [ $ST -ne 0 ]; then 
	echo >&2 "$Errmsg ruby (version >=2.0) is required.  Aborting."; exit 1;
fi

### check availablity of GNU parallel
if [ "$ncpus" -gt 1 ]; then 
	command -v parallel >/dev/null 2>&1 || { echo >&2 "$Errmsg parallel (GNU parallel) is not available.  Aborting."; exit 1; }
fi
# }}} check dependencies


# {{{ after run function
function after_run(){
  endTime=$(LC_ALL=C date +"%Y-%m-%d %H:%M:%S %z")

  if [[ $1 -gt 0 ]] ; then
    echo "$Errmsg run failed: $endTime" > "$logdir/$startTime.$jobname.error"
    echo "$Errmsg process is killed: $endTime" |tee -a "$flog"
    exit 1
  else
    echo "$Sccmsg run finished: $endTime" > "$logdir/$startTime.$jobname.success"
  fi
}
### }}} after run function


# {{{ input command
read -r -d '' incmdlog <<EOF

[1;32m===== command line[0m

$ $incmd

[1;32m===== log file[0m

$flog

[1;32m===== check version: $PROGNAME[0m

$VERSION

EOF
# }}} input command


### main

## write input command
echo "$incmdlog" |tee -a $flog

## trap Ctrl-C etc...
trap 'after_run 1' 1 2 3 9 15

## run
rake -f $rakefile \
	outdir="$outdir" query="$query" refpkg="$refpkg" outdir_exist="$outdir_exist" \
	evalue="$evalue" minseqlen="$minseqlen" minhmmlen="$minhmmlen" \
	mafft_method="$mafft_method" extract_levels="$extract_levels" trim_option="$trim_option" \
	chunk_size="$chunk_size" ncpus="$ncpus" only_detect="$only_detect" \
	2>&1 |tee -a $flog
st=$(( ${PIPESTATUS[0]} + ${PIPESTATUS[1]} ))
after_run $st

